#!/usr/bin/env bash
#
# A wizard - walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library - delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear - wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" - opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later - it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" - clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." - a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." - a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL - open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

# pause "msg" - wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" - y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY - current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" - read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" - like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE - upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE - set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name - gh not ready; set it later"
}

# set_var NAME VALUE - set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name - gh not ready; set it later"
}

# finish - clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES - author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "npm Account Setup and Package Publishing"

# ── Stage 1: Create npm Account ───────────────────────────────────────────
stage "Create npm Account & Verify Email"
say "First, we'll create your public npm account on npmjs.com."
open_url "https://www.npmjs.com/signup"
step "Enter your desired Username, Email address, and Password."
step "Check the agreement box and click 'Create an Account'."
step "Check your email for the verification code and enter it to verify your account."
pause "Press Enter once your email is verified and you are logged into npmjs.com"

# ── Stage 2: Generate npm Access Token ────────────────────────────────────
stage "Generate npm Access Token for GitHub Actions"
say "We will generate an Automation Token so GitHub Actions can publish releases."
open_url "https://www.npmjs.com/settings/~/tokens"
step "Click 'Generate New Token' -> select 'Classic Token'."
step "Set Token Name: 'omp-gemini-image-ci'."
step "Select Type: 'Automation' (this allows CI publish without 2FA blockage)."
step "Click 'Generate Token' and copy the resulting string (starts with npm_)."
ask_secret NPM_TOKEN "Paste your npm Automation Token:"
set_secret NPM_TOKEN "$NPM_TOKEN"

# ── Stage 3: Authenticate Local pnpm ──────────────────────────────────────
stage "Log in with pnpm Locally"
say "Now we will log into npm on your terminal using pnpm."
step "In the prompt below, enter your npm username, password, and email."
step "When prompted for OTP, enter the code sent to your email/authenticator app."
pause "Press Enter to launch pnpm login"

if pnpm login; then
  CURRENT_USER=$(pnpm whoami 2>/dev/null || echo "authenticated user")
  printf '  %s✓ Logged in as: %s%s\n' "$GREEN" "$CURRENT_USER" "$RESET"
else
  warn "pnpm login did not complete successfully. You can retry running 'pnpm login' manually."
fi
pause "Press Enter to proceed to publishing"

# ── Stage 4: Publish Package ──────────────────────────────────────────────
stage "Publish omp-gemini-image to npm"
say "Publishing version 0.1.0 of omp-gemini-image to the public npm registry."
step "Verifying package contents..."
pnpm pack --dry-run
printf '\n'
if confirm "Ready to publish omp-gemini-image to npm?"; then
  say "Publishing package..."
  if pnpm publish --access public --no-git-checks; then
    printf '  %s✓ Published omp-gemini-image successfully!%s\n' "$GREEN" "$RESET"
  else
    warn "Publish command failed. Review the output above."
  fi
else
  say "Publish skipped. You can run 'pnpm publish --access public' at any time."
fi
pause "Press Enter to proceed to verification"

# ── Stage 5: Verification ─────────────────────────────────────────────────
stage "Verify Package & Test Installation"
say "Checking the live package on npm registry."
open_url "https://www.npmjs.com/package/omp-gemini-image"
step "Verify that omp-gemini-image shows up on npmjs.com."
printf '\n'
say "Anyone can now install your plugin via Oh My Pi or standard Pi:"
printf '  %s%somp plugin install omp-gemini-image%s\n' "$BOLD" "$GREEN" "$RESET"
printf '  %s%spi install npm:omp-gemini-image%s\n\n' "$BOLD" "$GREEN" "$RESET"
pause "Press Enter to finish"

finish
